# Generated by Django 4.2.7 on 2024-03-19 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_wishlist_review_productfaq_notification_coupon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='vendors',
            new_name='vendor',
        ),
    ]
