# Generated by Django 4.2.7 on 2024-03-19 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_rename_vendors_product_vendor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-title'], 'verbose_name_plural': 'Categories'},
        ),
    ]
