# Generated by Django 4.2.7 on 2024-04-13 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_cartorderitem_coupon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupon',
            old_name='Vendor',
            new_name='vendor',
        ),
    ]
